### ISSUE TITLE
parsimonious incompatibility

### ISSUE THREAD

**Issue by alexalittle** [brendano/gfl_syntax#21]
When running gfl_parser.py, I got this error:

Traceback (most recent call last):
  File "gfl_parser.py", line 492, in <module>
    test('gfl1.peg')
  File "gfl_parser.py", line 481, in test
    p = parse([], x, grammar, check_semantics=True, ignore_order=True)
  File "gfl_parser.py", line 387, in parse
    p = grammar.parse(gfl)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/grammar.py", line 112, in parse
    return self.default_rule.parse(text, pos=pos)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 107, in parse
    node = self.match(text, pos=pos)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 124, in match
    raise error
parsimonious.exceptions.ParseError: Rule 'E' didn't match at '> dog' (line 1, column 57).

We discovered that it was an incompatibility with the newer versions of parsimonious. Parsimonious 0.3 works fine!

**Comment by nschneid** [comment]
Thanks! README now indicates the required version.
